---
title: "CW"
author: "XUCHEN GE"
date: "2021/1/10"
output: html_document
---

```{r setup, include=FALSE}
```library(spatstat)
library(here)
library(sp)
library(rgeos)
library(maptools)
library(GISTools)
library(tmap)
library(sf)
library(geojson)
library(geojsonio)
library(tmaptools)
library(tidyverse)
library(sf)
library(stringr)
library(tidymodels)
library(highcharter)
library(tidyverse)
library(downloader)
library(rgdal)
library(sf)
library(ggplot2)
library(reshape2)
library(plotly)
library(raster)
library(downloader)
library(rgdal)
library(raster)
library(fpc)
library(dbscan)
library(spdep)
#####england by local authority 
e_w = st_read(here::here("Population_Density_in_England_and_Wales_per_District_mid_year_2018-shp",
                         "Population_Density_in_England_and_Wales_per_District_mid_year_2018.shp"))%>%
  st_transform(.,27700)


#OSM <- st_read(here::here("england-latest-free.shp (1)",
#                          "gis_osm_landuse_a_free_1.shp"))%>%
# filter(fclass =='house')
###region in England
regionmap <- st_read(here::here("Region__December_2015__Boundaries-shp",
                             "Region__December_2015__Boundaries.shp"))
 
region <- read_csv("region_cases.csv")
#################################################
regionmap <- regionmap %>%
  merge(.,
        region,
        by.x="rgn15cd",
        by.y="areaCode")
tmap_mode("plot")
tm_shape(regionmap) +
  tm_polygons("cum_cases",
              style="jenks",
              palette="PuBu",
              midpoint=NA,
              popup.vars=c("areaName", "cum_cases"),
              title="Cumulative cases")+
  tm_compass(position = c("right", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("right", "bottom")) +
  tm_layout(legend.position = c("left", "top"))


###############################
cases = read_csv("englandcases.csv")
auto = read_csv ("auto.csv")#####without isles
eng <- e_w %>%
dplyr::filter(str_detect(lad11cd, "^E0"))%>%
            left_join(.,
            cases,
            by=c("lad11cd" = "area_code"))




############################

###########################
eng%>%
  head(.,n=10)

tmap_mode("plot")

#########
tm_shape(eng) +
  tm_polygons("cum_cases",
              style="jenks",
              palette="BuPu",
              midpoint=NA,
              popup.vars=c("area_name", "cum_cases"),
              title="Cumulative cases")+
  tm_compass(position = c("right", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("right", "bottom")) +
  tm_layout(legend.position = c("left", "top"))
  
#########population density  
tm_shape(eng) +
  tm_polygons("engpop_density",
              style="jenks",
              palette="PuBu",
              midpoint=NA,
              popup.vars=c("area_name", "engpop_density"),
              title="Population Density")+
  tm_compass(position = c("right", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("right", "bottom")) +
  tm_layout(legend.position = c("left", "top"))

############################################################## 


summary(cases)

#########################################################
auto = read_csv ("auto.csv")

remove_isle <-e_w%>%
  merge(.,
        auto,
        by.x="lad11cd",
        by.y="area_code")
########################
enguse <- remove_isle %>%
  dplyr::select(lad11cd,cum_cases,engpop_density,area_name,logcase)
##########Descripivate Statistics
# check data type
Datatypelist <- enguse %>% 
  st_drop_geometry()%>%
  summarise_all(class) %>%
  pivot_longer(everything(), 
               names_to="All_variables", 
               values_to="Variable_class")

Datatypelist

###############################################################################



#######spatial autocorrelation 
#######################################################################

########################
mydata1<- enguse %>%
  st_drop_geometry()%>%
  dplyr::select(c(logcase, cum_cases))

########before transformation 
histplot <- ggplot(data=mydata1, aes(x=cum_cases))+
  ggtitle("Cumulative cases (Before normalization)")+
  xlab("Number of cases")+
  ylab("Frequency")+
  theme(plot.title=element_text(hjust=0.5))

histplot +geom_histogram()

histplot <- ggplot(data=mydata1, aes(x=logcase))+
  ggtitle("Cumulative cases (After normalization)")+
  xlab("Number of cases")+
  ylab("Frequency")+
  theme(plot.title=element_text(hjust=0.5))

histplot +geom_histogram()


########################


coordsW <- enguse%>%
  st_centroid()%>%
  st_geometry()

plot(coordsW,axes=TRUE)

#create a neighbours list

england_nb <- enguse %>%
  poly2nb(., queen=T)

#plot them
plot(england_nb, st_geometry(coordsW), col="red")

plot(enguse$geometry, add=T)

#create spatial weights from weight 
england.lw<-england_nb %>%
  nb2listw(.,style="C")

head(england.lw$neighbours)

#########spatial auto-correlation
#######global moran I test
casesglobal <- enguse %>%
  pull(logcase) %>%
  as.vector()%>%
  moran.test(., england.lw)

casesglobal
################got global moran I
#################Geary's C
case_c<- 
  enguse %>%
  pull(logcase) %>%
  as.vector()%>%
  geary.test(., england.lw)

case_c

##############global G 

G_case <- 
  enguse %>%
  pull(logcase) %>%
  as.vector()%>%
  globalG.test(., england.lw)

G_case
###################################local moran I
I_england_local <-enguse %>%
  pull(logcase)%>%
  as.vector%>%
  localmoran(.,england.lw)%>%
  as_tibble()

slice_head(I_england_local,n=6)
###########################################


enguse <- enguse %>%
  mutate(case_G = as.numeric(Gi_eng))
##############
breaks1<-c(-1000,-2.58,-1.96,-1.65,1.65,1.96,2.58,1000)

MoranColours<- rev(brewer.pal(8, "RdGy"))
tm_shape(enguse) +
  tm_polygons("Iz_cases",
              style="fixed",
              breaks=breaks1,
              palette=MoranColours,
              midpoint=NA,
              title="Local Moran's I")+
  tm_layout(legend.position = c("left", "top"))+
  tm_compass(position = c("right", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("right", "bottom"))
##########
GIColours<- rev(brewer.pal(8, "RdBu"))

tm_shape(enguse) +
  tm_polygons("case_G",
              style="fixed",
              breaks=breaks1,
              palette=GIColours,
              midpoint=NA,
              title="Gi*")+
  tm_layout(legend.position = c("left", "top"))+
  tm_compass(position = c("right", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("right", "bottom"))



###########################



